export default {
    "login": "TeAmP0is0N",
    "id": 42641738,
    "node_id": "MDQ6VXNlcjQyNjQxNzM4",
    "avatar_url": "https://avatars2.githubusercontent.com/u/42641738?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/TeAmP0is0N",
    "html_url": "https://github.com/TeAmP0is0N",
    "followers_url": "https://api.github.com/users/TeAmP0is0N/followers",
    "following_url": "https://api.github.com/users/TeAmP0is0N/following{/other_user}",
    "gists_url": "https://api.github.com/users/TeAmP0is0N/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/TeAmP0is0N/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/TeAmP0is0N/subscriptions",
    "organizations_url": "https://api.github.com/users/TeAmP0is0N/orgs",
    "repos_url": "https://api.github.com/users/TeAmP0is0N/repos",
    "events_url": "https://api.github.com/users/TeAmP0is0N/events{/privacy}",
    "received_events_url": "https://api.github.com/users/TeAmP0is0N/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Rohit Singh Rathaur",
    "company": null,
    "blog": "https://teamp0is0n.github.io/rohit-rathaur.github.io/",
    "location": "Jharkhand",
    "email": null,
    "hireable": true,
    "bio": "Mathematics & Computing at Birla Institute Of Technology, Mesra, India\r\n",
    "public_repos": 35,
    "public_gists": 2,
    "followers": 17,
    "following": 16,
    "created_at": "2018-08-23T11:14:20Z",
    "updated_at": "2019-10-17T08:33:40Z"
};